[conclusions]
== Conclusions

This work has presented the development of the design and specification, for the implementation and programming, of a prototype for a CPU with a small but functional architecture, based on an improved variant for the Emil Post’s Machine. The logical design was specified using RTL methodology and is perfectly codable with any hardware description language, such as VHDL or Verilog. In particular, in the appendixes of this work, details are provided to obtain a functional prototype by synthesizing and implementing a VHDL project, within the Xilinx Vivado environment, and the corresponding binary sequence loading for the FPGA of a low-cost development board. 

The resulting system can be easily programmed in machine language, starting from a source program, with instructions and syntax similar to those of a modern assembler language. The author is convinced that the proposed architecture, being so simple and affordable, allows those interested to have a tool to develop, experiment and teach/learn the fundamental concepts of software and hardware systems, such as the algorithm, the machine language, the assembler language, the micro-code, micro-processing, RTL design and coding of digital systems with hardware description languages, all of which can be of great help within the teaching-learning process of courses with related topics, such as courses on logical design, digital systems programming and micro-processing systems, among others.
